[package]
name = "dreamland"
description = "A cross-platform image gallery application"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
name = "dreamland_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "dreamland"
path = "src/main.rs"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
dreamland-core = { path = "../crates/dreamland-core" }
dreamland-site-yandere = { path = "../crates/dreamland-site-yandere" }
dreamland-sites = { path = "../crates/dreamland-sites" }
dreamland-runtime = { path = "../crates/dreamland-runtime" }
tauri.workspace = true
