[workspace]
members = [
  "crates/dreamland-core",
  "crates/dreamland-moe",
  "crates/dreamland-sites",
  "crates/dreamland-site-pixiv",
  "crates/dreamland-site-twitter",
  "crates/dreamland-site-konachan",
  "crates/dreamland-site-yandere",
  "crates/dreamland-runtime",
  "src-tauri",
]
resolver = "2"

[workspace.package]
authors = ["azusachino"]
edition = "2021"
repository = "https://github.com/azusachino/dreamland"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
base64 = "0.22"
dirs = "5"
reqwest = { version = "0.11", features = ["json"] }
rusqlite = { version = "0.32", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2", features = [] }
tauri-build = { version = "2", features = [] }
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt", "sync", "time"] }
toml = "0.8"
uuid = { version = "1.0", features = ["v4"] }
