[package]
name = "dreamland"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/azusachino/dreamland"

[dependencies]
anyhow = "1"
thiserror = "2"


tokio = { version = "1", features = ["full"] }
