[package]
name = "dreamland-sites"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
dreamland-core = { path = "../dreamland-core" }
dreamland-site-pixiv = { path = "../dreamland-site-pixiv" }
dreamland-site-yandere = { path = "../dreamland-site-yandere" }
dreamland-site-twitter = { path = "../dreamland-site-twitter" }
